<?php

require_once $_SERVER["DOCUMENT_ROOT"]."/connection.php";

$room_package_1_res = mysqli_query($con, "SELECT * from rooms WHERE package_no = 1");
$room_package_2_res = mysqli_query($con, "SELECT * from rooms WHERE package_no = 2");
$room_package_3_res = mysqli_query($con, "SELECT * from rooms WHERE package_no = 3");

$room_package_1 = mysqli_fetch_all($room_package_1_res, MYSQLI_ASSOC);
$room_package_2 = mysqli_fetch_all($room_package_2_res, MYSQLI_ASSOC);
$room_package_3 = mysqli_fetch_all($room_package_3_res, MYSQLI_ASSOC);

$rooms = [];

array_push($rooms, [ "package_no" => 1, "limit" => 15, "rooms" => $room_package_1 ]);
array_push($rooms, [ "package_no" => 2, "limit" => 15, "rooms" => $room_package_2 ]);
array_push($rooms, [ "package_no" => 3, "limit" => 15, "rooms" => $room_package_3 ]);


$room_items = 3;

?>
  
<!-- Autogenerated script from the server -->
<script>
  var rooms = <?= json_encode($rooms) ?>
</script>
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Reservation</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Reservation</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->`
</div>

<div class="container-fluid">
<div class="row w-100 gap-4">
        <div class="col">
            <div class="card w-100">
                <div class="card-header">
                    <h3 class="m-0" >Summary</h3>
                </div>
                <div class="card-body">
                    <div class="d-flex flex-column">
                    <div id="inquiry-status" class="rounded bg-primary text-light p-4"></div>
                    <div class="mt-2">
                        <b>Price</b>
                        <h2 id="price-indicator">Php 0.00</h2>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <form class="w-100 bg-light p-4 rounded" method="POST">
                <div class="mb-3">
                    <h2>Inquiry</h2>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="expected-date">Expected Date:</label>
                    <input class="form-control" type="date" id="cbodate" name="expecteddate" required>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="packageno">Selected Package:</label>
                    <select class="form-control" id="cbopackage" name="packageno" required>
                        <option value="0" disabled>--SELECT--</option>
                        <option value="1">Package 1</option>
                        <option value="2">Package 2</option>
                        <option value="3">Package 3</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="packageno">Selected Room:</label>
                    <select class="form-control" id="cboroom" name="room_no" required>   
                    </select>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label class="form-label" for="cboduration">Stay Duration:</label>
                        <select class="form-control" id="cboduration" name="stayduration" required>
                            <option value="0" disabled selected>--SELECT--</option>
                            <option value="3">3 Hours</option>
                            <option value="6">6 Hours</option>
                            <option value="9">9 Hours</option>
                            <option value="12">12 Hours</option>
                            <option value="24">24 Hours</option>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label" for="cboperson">Person: </label>
                        <input class="form-control" type="number" name="person" id="cboperson" required>
                    </div>
                </div>
                <div class="mb-3">
                    <input type="submit" id="reserve-submit" class="btn btn-success" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>

<script src="/assets/js/clientReservation.js" defer></script>