<?php

require_once $_SERVER["DOCUMENT_ROOT"]."/connection.php";

$room_package_1_res = mysqli_query($con, "SELECT * from rooms WHERE package_no = 1");
$room_package_2_res = mysqli_query($con, "SELECT * from rooms WHERE package_no = 2");
$room_package_3_res = mysqli_query($con, "SELECT * from rooms WHERE package_no = 3");

$room_package_1 = mysqli_fetch_all($room_package_1_res, MYSQLI_ASSOC);
$room_package_2 = mysqli_fetch_all($room_package_2_res, MYSQLI_ASSOC);
$room_package_3 = mysqli_fetch_all($room_package_3_res, MYSQLI_ASSOC);

$rooms = [];

array_push($rooms, [ "package_no" => 1, "rooms" => $room_package_1 ]);
array_push($rooms, [ "package_no" => 2, "rooms" => $room_package_2 ]);
array_push($rooms, [ "package_no" => 3, "rooms" => $room_package_3 ]);


$room_items = 3;

$loggedIn = isset($_SESSION["customer_no"]);
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="res/logo.png">
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/modal.css">
    <link rel="stylesheet" href="/assets/css/guest-reservation.css">
    <link rel="icon" href="favicon.png">
    <!--font-awesome-->
    <link rel="stylesheet" href="/plugins/fontawesome/css/all.min.css">
    <!--font-family-google-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/navbar.css">
    <title>TRF Hotel- Campaňeros Hotel </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous" defer></script>

    <script src="/plugins/jquery/jquery-3.7.1.min.js"></script>
    <link href="/plugins/sweetalert2/sweetalert2.min.css" rel="stylesheet">

    
    <script src="script.js" defer></script>
    <script src="/plugins/sweetalert2/sweetalert2.all.min.js" defer></script>
    <script src="/assets/js/navbar.js" defer></script>
    <script src="/assets/js/inquiry.js" defer></script>
</head>

<body>
    <!-- Autogenerated script from the server -->
    <script>
        var rooms = <?= json_encode($rooms) ?>
    </script>
    <!-- Navbar --------------------------------------------------------------------------------->
    <header>
        <nav id="custom-navbar">
            <a href="/" id="custom-navbar-logo">
                <img src="/favicon.png" alt="">
            </a>
            <div id="custom-navbar-nav">
                <div id="custom-navbar-lists" class="d-none d-md-block">
                    <a href="/">Home</a>
                    <a href="#main-desc">Facilities</a>
                    <a href="#about">About Us</a>
                    <a href="#FAQ">FAQ</a>
                    <a href="#inquiry">Inquire</a>
                    <a href="#package" class="btn btn-success">Book Now!</a>
                </div>
                <div id="custom-navbar-actions">
                    <?php if ($loggedIn): ?>
                        <a class="btn btn-primary" href="/client/dashboard.php">Dashboard</a>
                    <?php else: ?>
                        <a class="btn btn-primary" href="/login.php">Log In</a>
                    <?php endif ?>
                    <button class="btn d-block d-md-none" id="dropdown-toggle">
                        <i class="fas fa-bars text-light"></i>
                    </button>
                </div>
            </div>
        </nav>
        <aside id="custom-dropdown">
            <div id="custom-dropdown-container">
                <div id="custom-dropdown-lists">
                    <a href="/">Home</a>
                    <a href="#main-desc">Facilities</a>
                    <a href="#about">About Us</a>
                    <a href="#FAQ">FAQ</a>
                    <a href="#inquiry">Inquire</a>
                    <a href="#package" class="btn btn-success">Book Now!</a>
            </div>
            </div>
        </aside>
    </header>


    <!-- Active class to the current button (highlight it)-->
    <script>
        var head = document.getElementById("one-nav");
        var btns = head.getElementsByClassName("btn");
        for (const button of btns) {
            button.addEventListener("click", function() {
                var current = document.getElementsByClassName("active");
                current[0].className = current[0].className.replace("active", "");
                this.className += " active";
            });
        }
    </script>
    <main>

        <!--Carousel---------------------------------------------------------------------------------->

        <section id="main-carousel">
            <br><br><br><br><br><br><br><br><br><br>
            <h1>TRF Hotel  <span> - Campaňeros Hotel</span><br>Muzon CSJDM</h1>
            <h1 id="intro">The perfect place to stay a little longer</h1>
            <br><br>
        </section>

        <!-- Facilities ---------------------------------------------------------------------->
        <section id="main-desc">
            <div class="container">
                <h2 class="title">TRF Hotel- campaňeros Hotel </h2>
                <div class="main-container">
                    <?php
                    $sqlshowpic = mysqli_query($con, "SELECT * from gallery_image");
                    while ($result = mysqli_fetch_assoc($sqlshowpic)) {
                    ?>
                        <div class="image">
                            <img class="expandable" src="/admin/ref/<?php echo $result['gallery_image'] ?>" alt="white sample" />
                        </div>
                    <?php
                    }
                    ?>

                </div>
                <div class="popup-image">
                    <span>&times;</span>
                    <img src="/assets/img/TRFront.jpg" alt="">
                    </p>
                </div>
            </div>
        </section>

        <!-- PACKAGE PRICINGLISTS -->
        <section id="package">
            <div class="container">
                <?php
                ?>
                <!-- PACKAGES -->
                <h2 class="title">Packages</h2>
                <br>
                    <div class="package-price-lists">
                        <div class="package-price-list">
                            <h3>Package 1</h3>
                            <ul>
                                <?php 
                                    foreach($room_package_1 as $room):
                                        $price_list = json_decode($room["price_list"], true); 
                                ?>
                                <li>Room <?= $room["room_no"] ?> - Starts at Php <?= $price_list[0]["price"] ?></li>
                                <?php endforeach ?>
                            </ul>
                            <a href="/reserve.php?package=1" class="btn btn-primary w-100">Reserve Now</a>
                        </div>
                        <div class="package-price-list">
                            <h3>Package 2</h3>
                            <ul>
                                <?php 
                                    foreach($room_package_2 as $room):
                                        $price_list = json_decode($room["price_list"], true); 
                                ?>
                                <li>Room <?= $room["room_no"] ?> - Starts at Php <?= $price_list[0]["price"] ?></li>
                                <?php endforeach ?>
                            </ul>
                            <a href="/reserve.php?package=2" class="btn btn-primary w-100">Reserve Now</a>
                        </div>
                        <div class="package-price-list">
                            <h3>Package 3</h3>
                            <ul>
                                <?php 
                                    foreach($room_package_3 as $room):
                                        $price_list = json_decode($room["price_list"], true); 
                                ?>
                                <li>Room <?= $room["room_no"] ?> - Starts at Php <?= $price_list[0]["price"] ?></li>
                                <?php endforeach ?>
                            </ul>
                            <a href="/reserve.php?package=3" class="btn btn-primary w-100">Reserve Now</a>
                        </div>
                    </div>
                </div>
                </div>
            </div>

        </section>

        <!--ABOUT US---------------------------------------------------------->
        <section id="about">
            <div class="container" id="about-container">
                <h2 class="title">ABOUT US</h2>
                <br>
                <p>
                        TRF Hotel Management was established on April 01,2010, manage by Ms.Maricel Alforo the owner of the TRF Hotel of City San Jose del Monte, Bulacan, And inspired with the owner’s. TRF Hotel  is located in Poblacion 1 City of San Jose del Monte, Bulacan, Philippines. They offer TRF Hotel reservation for any events or occasions such as birthdays, ideal for friends, family or company gatherings. Facilities that can be found in the hotel have a rooms, billiards and function hall and if you want to reservation of there resort and located at Princess TRF Beach & Hotel, Barangay Saysain Bagac Bataan.
                </p>
                <br><br>
                <div id="about-mv-container">
                    <div class="about-mv-item">
                        <br>
                        <i class="fa fa-globe"></i>
                        <br>
                        <h3>VISION</h3>
                        <br>
                        <hr>
                        <br>
                        <p>A place that you can use for your family, office and friends recreation and team building activities.
                        </p>
                        <br>
                    </div>
                    <div class="about-mv-item">
                        <br>
                        <i class="fa fa-book"></i>
                        <h3>MISSION</h3>
                        <br>
                        <hr>
                        <br>
                        <p>To provide affordable and quality of TRF hotel for the relaxing moment of your family. We promise to provide a complete service with integrity
                        </p>
                        <br>
                    </div>
                </div>
            </div>
        </section>

        <!-- FAQ -->
        <section id="FAQ">
            <div class="container">
                <h2 class="title">Frequently Ask Questions:</h2>
                <br>
                <div id="faq-container">
                    <img class="expandable" src="/assets/img/FAQ1.jpg">
                    <img class="expandable" src="/assets/img/FAQ2.jpg">
                    <img class="expandable" src="/assets/img/FAQ3.jpg">
                    <img class="expandable" src="/assets/img/FAQ4.jpg">
                </div>
                <hr>
            </div>
        </section>

        <!--Inquiries------------------------------------------------------------------------------>
        <section class="inquiry" id="inquiry">
            <div class="container">
                <h2 class="title">INQUIRE HERE!</h2> 
                <br>     
                <form id="inquiryForm" method="post" autocomplete="off">
                    <p class="text-center">PERSONAL INFO.</p>
                    <p class="note" style="color:#CD5C5C; font-size: 15px; text-align:center;">NOTE: Please Fill out the Fields Correctly Before Submitting!</p>
                    <input type="text" placeholder="Full Name" name="inquiry_fullname" required>
                    <input type="email" placeholder="Email" name="email" required>
                    <input type="tel" placeholder="Contact" name="cpnumber" maxlength="11" oninput="restrictSpaces1(event);validateInput(this)" required>
                    <textarea rows="5" cols="55" name="message" placeholder="Type your question here!" id="message"></textarea>
                    <div class="index-btn-wrapper">
                        <button type="submit" class="index-btn">Submit</button>
                    </div>
                </form>
            </div>
        </section>

        <!-- TESTIMONIALS -->
        <section id="testimonials">
            <div class="container">
                <h2 class="title">FEEDBACK</h4>
            <div class="testimonial-container">
                <?php
                $sqlshowfeed = mysqli_query($con, "SELECT * FROM client_feed WHERE status-''");
                while ($result = mysqli_fetch_assoc($sqlshowfeed)): ?>

                    <div class="testimonial" style="overflow:hidden;padding:20px;">
                        <img src="/assets/img/profile3.jpg" alt="Testimonial 1">
                        <p style="padding:20px;">"<?php echo $result['message']; ?>"</p>
                        <span class="author" style="font-size:15px;"><?php echo $result['lname'] ?></span><br>
                        <span class="author" style="font-size:10px;"><?php echo $result['email'] ?></span>
                    </div>
                <?php endwhile ?>
            </div>

            </div>
        </section>
    </main>

    <!-- FOOTER -->
    <footer>
        <div class="row">
            <div class="col">
                <img src="/assets/img/TRF LOGO.jpg" class="logo">
            </div>

            <div class="col">
                <h3>Address: <div class="underline"><span></span></div>
                </h3>
                <p>Road Street</p>
                <p>Poblacion 1 , CSJDM Bulacan</p>
                <p>Region 3, ZIP No. 3023, Philippines</p>
                <br><br>
            </div>
            <div class="col">
                <h3>Contact Us: <div class="underline"><span></span></h3>
                <h4 class="num">09278985340</h4>
            </div>
            <div class="col">
                <h3>Embled Map:<div class="underline"><span></span></h3>
                <hr>
                <iframe src="https://www.google.com/maps/embed?pb=!3m2!1sen!2sph!4v1713194311643!5m2!1sen!2sph!6m8!1m7!1smnTZll4Fnh_Qo-KRj3nPWQ!2m2!1d14.80711228437814!2d121.0419296933778!3f281.002661890241!4f0.5017835721610737!5f0.7820865974627469" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> 
            </div>
            <div class="col">
                <h3>Follow us: <div class="underline"><span></span></h3>
                <br>
                <a href="https://www.facebook.com/profile.php?id=100092161653398...."><i class="fa-brands fa-facebook"></i></a>
                <a href="https://twitter.com/SaintMarkResort?t=7OTIq_kqXGlLWNd5XiEItg&s=09"><i class="fa-brands fa-twitter"></i></a>
                <a href="https://instagram.com/saintmark_resort0322?igshid=ZGUzMzM3NWJiOQ=="><i class="fa-brands fa-instagram"></i></a>
                <a href="https://www.tiktok.com/@saintmark00?_t=8cFK9kIOhIg&_r=1...."><i class="fa-brands fa-tiktok"></i></a>
            </div>
        </div>
        <br><br>
        <hr>
        <p class="copyright">La Concepcion College<br>Copyright © 2024 All Rights Reserved</p>
    </footer>
    <!--Ionicons-->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <!-- MODAL -->
    <script>
        //kunin ung bawat image na may class na main-container img 
        document.querySelectorAll('img.expandable').forEach(image => {
            //once na click eto mangyayare
            image.onclick = () => {
                //sa isa sa napindot na popup-image magdidisplay sya na block(nakikita na)
                document.querySelector('.popup-image').style.display = 'block';
                //lolocate din kung anong klaseng pic ung i didisplay sa pamamagitan ng SRC
                document.querySelector('.popup-image img').src = image.getAttribute('src');
            }
        });
        //kung na click naman ung popupimage span 
        document.querySelector('.popup-image span').onclick = () => {
            //magdidisplay na none
            document.querySelector('.popup-image').style.display = 'none';
        }
    </script>


</body>

</html>